import React, { useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { codexAdapter, genericJsonlAdapter } from "./core/adapters";
import { elapsedMs, formatElapsed, initialState, reduceEvent, type DisplayState } from "./core/reducer";
import { mockDelay, mockEvent, mockLength } from "./core/mock";
import type { AgentEvent, AgentStatus } from "./core/protocol";
import "./styles.css";
import "./sessions.css";

type Personality = "off" | "subtle" | "playful";
const faces: Record<AgentStatus, string> = { idle: "-_ -", thinking: "-_-", searching: ">_>", working: "-_-", command: "-_-", editing: "-_-", testing: "-_-", waiting: "?", approval: "?", complete: "^_^", error: "x_x" };
function useClock() { const [now, setNow] = useState(Date.now()); useEffect(() => { const i = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(i); }, []); return now; }
function App() {
  const [state, setState] = useState<DisplayState>(initialState); const [inspection, setInspection] = useState(false); const [help, setHelp] = useState(false); const [privacy, setPrivacy] = useState(false); const [personality, setPersonality] = useState<Personality>(() => (localStorage.getItem("personality") as Personality) || "subtle"); const [speed, setSpeed] = useState(1); const [playing, setPlaying] = useState(false); const now = useClock();
  const [sessionStates, setSessionStates] = useState<Record<string, DisplayState>>({}); const [selectedSession, setSelectedSession] = useState<string | null>(null); const selectedSessionRef = useRef<string | null>(null);
  const apply = (event: AgentEvent) => { const sessionId = typeof event.meta?.sessionId === "string" ? event.meta.sessionId : null; if (!sessionId) { setState((old) => reduceEvent(old, event)); return; } setSessionStates((old) => { const sessionName = typeof event.meta?.sessionName === "string" ? event.meta.sessionName : sessionId.slice(0, 8); const base = old[sessionId] ?? { ...initialState, recent: [], files: [], plan: [], sessionName }; const next = reduceEvent(base, event); if (!selectedSessionRef.current) { selectedSessionRef.current = sessionId; setSelectedSession(sessionId); setState(next); } else if (selectedSessionRef.current === sessionId) setState(next); return { ...old, [sessionId]: next }; }); };
  useEffect(() => { const sync = () => invoke<unknown[]>("codex_desktop_sessions").then((events) => { if (!Array.isArray(events) || events.length === 0) throw new Error("No Codex desktop sessions found"); events.forEach((payload) => { const normalized = genericJsonlAdapter.ingest(payload); if (normalized) apply(normalized); }); }).catch((error) => apply({ version: 1, id: `desktop-adapter-error-${Date.now()}`, timestamp: new Date().toISOString(), kind: "error", status: "error", label: "ADAPTER ERROR", detail: String(error) })); sync(); const timer = window.setInterval(sync, 1000); const unlisten = listen<unknown>("big-agent:event", (e) => { const normalized = genericJsonlAdapter.ingest(e.payload) ?? codexAdapter.ingest(e.payload); if (normalized) apply(normalized); }); return () => { window.clearInterval(timer); unlisten.then((f) => f()).catch(() => undefined); }; }, []);
  useEffect(() => { if (!playing) return; let cancelled = false; let index = 0; const play = () => { if (cancelled) return; apply(mockEvent(index)); const delay = mockDelay(index++, speed); window.setTimeout(play, delay); }; play(); return () => { cancelled = true; }; }, [playing, speed]);
  useEffect(() => { const onKey = (e: KeyboardEvent) => { if (e.key.toLowerCase() === "f") invoke("toggle_fullscreen").catch(() => document.documentElement.requestFullscreen?.()); if (e.key === "Escape") { invoke("exit_fullscreen").catch(() => document.exitFullscreen?.()); setHelp(false); } if (e.key.toLowerCase() === "i") setInspection((x) => !x); if (e.key.toLowerCase() === "a") invoke("toggle_always_on_top"); if (e.key === "?") setHelp((x) => !x); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  useEffect(() => localStorage.setItem("personality", personality), [personality]);
  const fileLines = privacy ? [] : state.files.slice(0, 4); const detail = privacy && state.detail ? "Agent activity in progress" : state.detail;
  const tinyFace = personality === "off" ? "" : personality === "playful" && state.status === "working" && elapsedMs(state, now) > 25 * 60_000 ? "..." : faces[state.status];
  const beginDrag = (event: React.MouseEvent<HTMLElement>) => { if ((event.target as HTMLElement).closest("button, select")) return; getCurrentWindow().startDragging().catch(() => undefined); };
  const selectSession = (id: string) => { const next = sessionStates[id]; if (!next) return; selectedSessionRef.current = id; setSelectedSession(id); setState(next); };
  return <main className={`app status-${state.status} ${state.attention ? "needs-attention" : ""}`}>
    <header data-tauri-drag-region onMouseDown={beginDrag}><div className="identity" data-tauri-drag-region><b>BIG AGENT</b><span>{state.project}</span><span>{state.branch}</span></div><div className="top-actions"><button onClick={() => setInspection(!inspection)} aria-label="Toggle inspection">{inspection ? "AMBIENT" : "INSPECT"}</button><i className="status-dot" title={state.status} /></div></header>
    {Object.keys(sessionStates).length > 1 && <nav className="session-switcher" aria-label="Active Codex sessions">{Object.entries(sessionStates).map(([id, session], index) => <button key={id} className={selectedSession === id ? "selected" : ""} onClick={() => selectSession(id)}><i className={`mini-dot mini-${session.status}`} /><span>{index + 1}</span><small>{session.sessionName}</small></button>)}</nav>}
    <section className="ambient" aria-live="polite"><div className="headline">{state.label}</div><div className={`detail ${fileLines.length ? "files" : ""}`}>{fileLines.length ? fileLines.map((file) => <span key={file}>{file}</span>) : detail.split("\n").map((line, i) => <span key={i}>{line}</span>)}</div>{state.startedAt && <time>{formatElapsed(elapsedMs(state, now))}</time>}<div className="face">{tinyFace}</div></section>
    <footer><span>{state.sessionName}</span><div className="controls"><button onClick={() => setPrivacy(!privacy)}>{privacy ? "PRIVATE" : "OPEN"}</button><button onClick={() => { setPlaying(!playing); if (!playing) apply(mockEvent(0)); }}>{playing ? "STOP DEMO" : "PLAY DEMO"}</button><select aria-label="Personality" value={personality} onChange={(e) => setPersonality(e.target.value as Personality)}><option value="off">Face off</option><option value="subtle">Face subtle</option><option value="playful">Face playful</option></select></div></footer>
    {inspection && <aside className="inspection"><div><h2>ACTIVITY</h2><p className="quiet">{state.status} · {formatElapsed(elapsedMs(state, now))}</p></div>{state.plan.length > 0 && <section><h3>PLAN</h3>{state.plan.map((p) => <p key={p}>{p}</p>)}</section>}<section><h3>RECENT</h3>{state.recent.slice(0, 12).map((event) => <article key={event.id}><b>{event.kind.replace(".", " ")}</b><span>{privacy ? "Activity hidden" : event.detail || event.command || event.label || event.status}</span></article>)}</section><div className="inspect-controls"><button onClick={() => setSpeed(speed === 1 ? 4 : 1)}>Demo {speed}×</button><button onClick={() => setState(initialState)}>Clear</button></div></aside>}
    {help && <div className="help" role="dialog"><button onClick={() => setHelp(false)}>×</button><h2>SHORTCUTS</h2><p><kbd>F</kbd> fullscreen <kbd>Esc</kbd> exit</p><p><kbd>I</kbd> inspection <kbd>A</kbd> always on top</p><p><kbd>?</kbd> this guide</p></div>}
  </main>;
}
createRoot(document.getElementById("root")!).render(<App />);
